# Generated by Django 5.1.4 on 2025-01-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0002_pessoa_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ativo2',
            field=models.BooleanField(default=True, verbose_name='Ativo2'),
        ),
    ]
