# Generated by Django 5.1.4 on 2025-01-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0003_pessoa_ativo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='ativo2',
        ),
    ]
