# Generated by Django 5.1.4 on 2025-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0004_remove_pessoa_ativo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='funcao'),
        ),
    ]
