# Generated by Django 5.1.4 on 2025-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0005_alter_pessoa_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Ativo'),
        ),
    ]
