# Generated by Django 5.1.4 on 2025-01-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0006_alter_pessoa_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
