# Generated by Django 5.1.4 on 2025-01-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0008_pessoa_nascimento2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nascimento2',
            new_name='nascimento',
        ),
    ]
