# Generated by Django 4.2.17 on 2025-01-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0009_rename_nascimento2_pessoa_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome', 'funcao']},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Funcao'),
        ),
    ]
